pybricks/pybricks-code

.gitignore
package.json
src/react-app-env.d.ts
src/sagas/.gitignore
src/sagas/mpy.ts
yarn.lock

This moves the .wasm file out of the static/js/ folder and into the
source tree. This way we can import it and webpack will pick it up
and version the file with a hash.
This fixes possibly running with an out of date file from the browser
cache and also fixes running offline.
The file extension had to be changed because there is a default rule in
webpack that matches the .wasm extension and causes the following error:
Failed to compile.
./src/sagas/mpy-cross.wasm
Module parse failed: magic header not detected
File was processed with these loaders:
* ./node_modules/file-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
Error: magic header not detected
The webpack configuration cannot be modified without ejecting
create-react-app or using something …

Rework web assembly inclusion

---

src/components/Toolbar.tsx
src/index.scss

Hi!
I was able to reproduce the issue described in #161 as follow:
* Open https://code.pybricks.com/
* Look for a link with a URI fragment in the documentation (e.g. https://docs.pybricks.com/en/latest/parameters.html#pybricks.parameters.Port)
* Click it.
=> Layout breaks as described in the issue.
After some googling I found that this behaviour comes from the browser itself.
The browser seems to force the parent frame to scroll to the position of the referenced URI fragment as well.
But as the toolbar is fixed, the rest of the content is scrolled under it.
Re-rendering after the link click fixes the layout (at least if done manually by removing and adding a CSS class in the dev tools).
I could not find a nice solution to force this re-rendering somehow. 
After looking deeper how the …

remove stickiness of toolbar to avoid breaking the layout

---

src/sagas/flash-firmware.ts

When the firmware blob is exactly a multiple of 10 times the packet
size, the last checksum request causes the reply to the last program
request to be missed (there is only a response from the hub to the very
last program request). The program response is received, then the
checksum response is received. Since the saga is waiting for the
checksum response first, the program response is discarded.
Fix by breaking out of the loop when the firmware has been fully
transferred before making the checksum request.
Fixes: pybricks/support#178

fix timeout when firmware size is 10x packet size

---

src/index.scss

Since the img is in a span, it was treated as text and added 4 pixelson the bottom for the descender height.
By using `display: block;` it won't be treated as text.
Fixes pybricks/pybricks-code#268

fix extra pixels under icons in buttons

---

.tool-versions
CONTRIBUTING.md

A depedency of blueprintsjs needs Python 2 to build.
https://github.com/palantir/blueprint/issues/4273

Add Python 2 dependency

---

src/notifications/NotificationAction.tsx
src/notifications/NotificationMessage.tsx
src/notifications/sagas.ts

55e724e8d84bc676987fa1f85effdf0194f84ef9 introduced `<p>` elements on notifications. however this is undesirable on the notification action text. This splits the Notification component into one that is pre change and one that is post change.
Fixes #394

Fix <p> element on notification action

---

package.json
yarn.lock

This brings in the updated code snippet style.
Also includes a new example for use in a video tutorial.

Bump @pybricks/ide-docs from 1.3.2 to 1.3.3

---

CHANGELOG.md
src/toolbar/ActionButton.tsx
src/toolbar/OpenFileButton.tsx
src/utils/monkey-patch.test.tsx
src/utils/monkey-patch.ts

This works around several bugs where tooltips don't close when expected.
Fixes: https://github.com/pybricks/pybricks-code/issues/275

toolbar: work around tooltip bugs

---

package.json
yarn.lock

We no longer need the jest module transform hack after this update since the browser-fs-access package.json now has proper exports.

yarn: update browser-fs-access

---

LICENSE

Assume the copyright text is copied automatically over all modules that need it.

bump copyright year to 2022

---

src/ble/sagas.ts

The 'gattserverdisconnected' event is called before the device is actually disconnected, so if the user tries to connect again immediately, the web browser will show a still "paired" device, but selecting this devices results in an infinite wait. This is a bug in Chromium, but we can work around it by adding a delay to give BlueZ time to actually disconnect the device.
Closes: https://github.com/pybricks/support/issues/600

ble/sagas: add workaround for BlueZ quirk

---

package.json
src/explorer/Explorer.tsx
src/utils/tree-renderer.tsx
yarn.lock

This reverts commit f0434b50edac11dc5935e49b3baf807cc3922d39.
This requires react >= v18

Revert "yarn: update react-complex-tree to v2.0.0"

---

CHANGELOG.md
public/manifest.json

"fullscreen" is for immersive apps like games (and is only available on Android currently which is why we didn't notice the app going fullscreen on desktop).
Fixes: https://github.com/pybricks/support/issues/867

public/manifest: change display to "standalone"

---

package.json
yarn.lock

This includes fixes for parsing additional Python syntax features added since Python 3.4 that are implemented by MicroPython.

package: bump @pybricks/python-program-analysis to v2.0.0

---

src/toolbar/ActionButton.tsx

https://github.com/palantir/blueprint/issues/5889
This was fixed in @blueprintjs/popover2 v1.12.1

toolbar/ActionButton: drop workaround for https://github.com/palantir/blueprint/issues/5889

---

CHANGELOG.md
src/editor/sagas.ts

When gotoError fails to activate a file, we need to show an error message, otherwise it just appears to the user that the button is broken.
Fixes: https://github.com/pybricks/support/issues/924

editor: show error message on fail to activate

---

CONTRIBUTING.md

Python 2 is no longer a dependency

---

src/ble/sagas.ts

Code depends on always receiving a didWrite/didFailToWrite, however when a hub disconnected, these tasks were being cancelled. Spawning protects them from cancellation.

ble/sagas: spawn ble writes

---

CONTRIBUTING.md

Update the documentation to list Node 18.x as the used Node version, rather than 12.x

Update documentation to specify Node 18.x

---

src/status-bar/status-bar.scss

Since this is display: flex, it needs min/max-height instead of plain height.

status-bar: fix height styling

---

CHANGELOG.md
src/editor/Editor.tsx

To avoid the Linux feature of pasting on middle click, we need to consume the mouse up event in the browser on middle click instead of mouse down.
This also sets the `selectionClipboard` editor option to false which should disable the feature altogether in the monaco editor but the setting seems to be broken in the browser[1].
[1]: https://github.com/microsoft/vscode/issues/181050
Fixes: https://github.com/pybricks/support/issues/1046

editor: don't paste on middle click to close tab

---

src/ble-pybricks-service/protocol.ts

This adds a new flag from Pybricks Profile v1.3.0 for documentation purposes. We currently don't support native modules in Pybricks Code so we aren't using this for now.

ble-pybricks-service/protocol: add UserProgramMultiMpy6Native6p1

---

CHANGELOG.md
src/explorer/sagas.test.ts
src/explorer/sagas.ts
src/fileStorage/actions.ts
src/fileStorage/sagas.test.ts
src/fileStorage/sagas.ts

When duplicating a file users expect the file to be opened as in other applications.
Fixes: https://github.com/pybricks/support/issues/1084

explorer: active file after duplicating

---

src/terminal/Terminal.tsx
src/terminal/terminal.scss

Since updating to Blueprintjs 5.x we can get aliasing artifacts on the cursor due to bad rendering of box-shadow. This overrides it with border instead.
https://github.com/xtermjs/xterm.js/issues/4580

terminal/Terminal: work around xterm cursor style issue

---

src/ble/alerts/translations/en.json

On iOS `getAvailability()` returns false if the app does not have permission to use the bluetooth adapter (which is what the spec says it should do if permission has not been granted), so clarify the reason for it not being available.
Also add a sneaky reference to WebBLE as a supported browser on iOS.

Clarify why bluetooth may not be available

---

.vscode/settings.json

The extension now has a default typescript config an "*" doesn't override it so we have to have an explicit "typescript" entry.

vscode: fix breaking change in psioniq extension

---

CHANGELOG.md
src/index.scss

This broke other stuff by making the overlay present even when there was no content.

revert overlay size hack

---

config/webpack.config.js

This is no longer needed since 71ada08 "build(deps): bump @pyodide/webpack-plugin from 1.2.0 to 1.3.2"

config: remove pyodide webpack hack

---

CHANGELOG.md
src/firmware/sagas.test.ts
src/firmware/sagas.ts

Mac users have recently been reporting failed firmware updates due to the hub disconnecting during the update process. This is likely due to the Mac sending packets faster than the hub can handle. This changes the arbitrary BLE firmware burst size from 10 to 8 to reduce the chance of the hub getting overwhelmed.

firmware/sagas: reduce BLE firmware burst size

---

CHANGELOG.md
src/terminal/sagas.test.ts
src/terminal/sagas.ts

Enable the stream option on the text decode for the stdout and uart stream handlers that pipe data to the terminal. This fixes improperly printing multibyte unicode characters that get split across multiple data packets.
A new decode is added for each different stream in case both are used at the same time.
Fixes: https://github.com/pybricks/support/issues/1743

terminal/sagas: fix handling multibyte unicode

---

src/ble-pybricks-service/actions.ts
src/ble-pybricks-service/protocol.ts
src/ble-pybricks-service/sagas.test.ts
src/ble-pybricks-service/sagas.ts
src/ble/reducers.test.ts
src/ble/sagas.ts
src/hub/actions.ts
src/hub/reducers.test.ts
src/hub/reducers.ts
src/hub/sagas.test.ts
src/hub/sagas.ts
src/toolbar/buttons/repl/ReplButton.test.tsx
src/toolbar/buttons/repl/ReplButton.tsx
src/toolbar/buttons/run/RunButton.test.tsx
src/toolbar/buttons/run/RunButton.tsx

Adding pybricks protocol v1.4.0 handling as a first step on to merge hubcenter feature in #2315.

Implemented pybricks protocol v1.4.0

---

src/ble-pybricks-service/actions.ts
src/ble-pybricks-service/protocol.ts
src/ble-pybricks-service/sagas.test.ts
src/ble-pybricks-service/sagas.ts
src/ble/reducers.test.ts
src/ble/sagas.test.ts
src/ble/sagas.ts
src/hub/reducers.test.ts
src/hub/reducers.ts
src/toolbar/buttons/run/RunButton.tsx

This is an alternative to #2343 and requires https://github.com/pybricks/pybricks-micropython/pull/312.

slots support

---

.yarn/patches/@types-w3c-web-usb-npm-1.0.10-82b33e05cb.patch
package.json
src/firmware/installPybricksDialog/InstallPybricksDialog.tsx
src/firmware/installPybricksDialog/hooks.ts
src/firmware/installPybricksDialog/index.ts
src/firmware/sagas.ts
src/usb/sagas.ts
yarn.lock

Minor implementation changes to make https://github.com/pybricks/support/issues/2318 work

Feature EV3 firmware flash - minor improvements
