pybricks/pybricks-code

- src/components/Terminal.tsx
- src/components/terminal-i18n.en.json
- src/components/terminal-i18n.ts
> Add Clear command to terminal context menu

- package.json
- src/components/editor-snippets.ts
- src/protocols/lwp3-bootloader.ts
- src/sagas/flash-firmware.ts
- yarn.lock
See discussion in https://github.com/pybricks/support/issues/119
> Rename CPlusHub to TechnicHub

- package.json
- yarn.lock
this documents supported browsers
> firmware update

- src/components/Terminal.tsx
- yarn.lock
Fixes https://github.com/pybricks/support/issues/170
> fix terminal losing focus after opening context menu 

- src/components/Terminal.tsx
Fixes https://github.com/pybricks/support/issues/172
> All CTRL+V in terminal

- src/components/ActionButton.tsx
- src/components/DocsButton.tsx
- src/components/ReplButton.tsx
- src/components/RunButton.tsx
- src/components/SaveAsButton.tsx
- src/components/StopButton.tsx
- src/components/Terminal.tsx
- src/components/Toolbar.tsx
- tsconfig.json
Just run and stop button have keys assigned for now.
> Add keyboard shortcuts to action buttons

- CONTRIBUTING.md
- README.md
Hi!
after falling into the trap myself (https://github.com/pybricks/support/issues/174), I propose to move the `Github Packages` section to the top of the `CONTRIBUTING.md` and add a note that this step is really really necessary. 😅 
Additionally I added a hint in the `README.md` pointing to the `CONTRIBUTING.md` file. Maybe this will help others to read the `CONTRIBUTING.md` more careful than I did. :-)
> Clarify how to contribute and point out github registry pitfall

- package.json
- yarn.lock
peer dependency for @testing-library/user-event
> add @testing-library/dom package

- src/components/editor-snippets.ts
Fix Code completion for "try:" snippets have a syntax error #213
> Fix for #213

- package.json
- yarn.lock
This includes the installation guide.
> Bump @pybricks/ide-docs from 1.1.0 to 1.1.1

- src/firmware/sagas.test.ts
- src/firmware/sagas.ts
- src/lwp3-bootloader/actions.ts
- src/lwp3-bootloader/sagas.test.ts
- src/lwp3-bootloader/sagas.ts
- src/utils/os.test.ts
- src/utils/os.ts
This works around some issues that have been observed on a specific Windows computer.
Issue: https://github.com/pybricks/support/issues/256
> firmware: add windows BLE hacks

- README.md
> README: update coverage badge

- .eslintrc.js
- config/jest/fileTransform.mjs
- package.json
- yarn.lock
This required converting the module that uses camelcase to mjs due to breaking change in camelcase.
> yarn: update camelcase

- src/app/constants.ts
Thanks David.
Does this PR "overrule" the previous one on LICENSE  #934 ?
So can I close or delete  #934
> Bump copyright year to 2022 in constants.ts

- src/hub/sagas.ts
Some of the math was assuming i was incremented with ++ instead += chunkSize.
> hub/sagas: fix handleDownloadAndRun slicing

- src/explorer/fileNameFormGroup/FileNameFormGroup.tsx
- src/explorer/fileNameFormGroup/translations/en.json
This was missed in https://github.com/pybricks/pybricks-code/commit/8b19ad58662186d2295a6241e8c3f84fbfd45809
> text: Don't say that dashes are allowed.

- CHANGELOG.md
- src/editor/Editor.test.tsx
- src/editor/Editor.tsx
Fixes: https://github.com/pybricks/support/issues/758
> editor: close tab on middle-click

- src/app/constants.ts
- src/ble/alerts/NoHub.tsx
- src/ble/alerts/translations/en.json
- src/editor/translations/en.json
- src/firmware/alerts/translations/en.json
- src/firmware/bootloaderInstructions/BootloaderInstructions.tsx
- src/firmware/bootloaderInstructions/bootloaderInstructions.scss
- src/firmware/bootloaderInstructions/translations/en.json
- src/firmware/installPybricksDialog/InstallPybricksDialog.tsx
- src/firmware/installPybricksDialog/translations/en.json
- src/firmware/restoreOfficialDialog/RestoreOfficialDialog.test.tsx
- src/firmware/restoreOfficialDialog/RestoreOfficialDialog.tsx
- src/firmware/restoreOfficialDialog/translations/en.json
- src/mpy/alerts/translations/en.json
- src/notifications/translations/en.json
- src/settings/Settings.test.tsx
- src/settings/translations/en.json
- src/toolbar/buttons/repl/translations/en.json
- src/toolbar/buttons/run/translations/en.json
- src/tour/Tour.tsx
- src/tour/translations/en.json
This makes several copy edits and a slightly bigger revision to to the install dialog:
This makes the introduction paragraph and closing paragraphs into specific instructions. 
original:
> copy edits and update to install dialog

- public/index.html
Fixes https://github.com/pybricks/support/issues/845
> index.html: Update meta content.

- package.json
- src/explorer/Explorer.tsx
- src/utils/tree-renderer.tsx
- yarn.lock
Includes fixes for breaking changes.
> yarn: update react-complex-tree to v2.0.0

- .eslintrc.js
- src/activities/hooks.ts
- src/app/hooks.ts
- src/components/toolbar/aria.ts
- src/editor/Editor.tsx
- src/editor/Welcome.tsx
- src/explorer/Explorer.tsx
- src/explorer/newFileWizard/NewFileWizard.tsx
- src/firmware/installPybricksDialog/InstallPybricksDialog.tsx
- src/firmware/installPybricksDialog/hooks.ts
- src/settings/hooks.ts
- src/terminal/Terminal.tsx
- src/toolbar/ActionButton.tsx
- src/tour/Tour.tsx
- src/utils/tree-renderer.tsx
Also fix all errors, which can lead to subtile bugs.
Mostly fixings deps and refactoring to make typescript happy.
> eslint: enable react-hooks checks

- .eslintrc.js
- src/alerts/UnexpectedErrorAlert.tsx
- src/app/constants.ts
- src/ble/alerts/NoHub.tsx
- src/firmware/alerts/NoDfuHub.tsx
- src/firmware/alerts/translations/en.json
- src/firmware/bootloaderInstructions/BootloaderInstructions.tsx
- src/firmware/bootloaderInstructions/translations/en.json
- src/firmware/dfuWindowsDriverInstallDialog/DfuWindowsDriverInstallDialog.tsx
- src/firmware/dfuWindowsDriverInstallDialog/dfuWindowsDriverInstallDialog.scss
- src/firmware/dfuWindowsDriverInstallDialog/translations/en.json
- src/firmware/sagas.ts
- src/notifications/sagas.ts
- src/sponsor/SponsorDialog.tsx
Fixes https://github.com/pybricks/support/issues/862, see discussion there.
> firmware/alerts: Add button to install USB driver.

- src/pybricksMicropython/python-worker.ts
This was introduced in Pyodide 0.22 and saves us from having to parse the message for the type.
Could also affect https://github.com/pybricks/support/issues/772 (but there is no known reproducible case to check it).
> pybricksMicropython: use new PythonError type property

- .github/workflows/codeql-analysis.yml
- .github/workflows/coverage.yml
- .github/workflows/release.yml
- .github/workflows/test-pull-request.yml
- fixes deprecation warnings
- fixes codecov upload failures
> github: update actions versions

- .github/workflows/codeql-analysis.yml
- .github/workflows/coverage.yml
- .github/workflows/release.yml
- .github/workflows/test-pull-request.yml
> github: update more actions versions

- src/status-bar/StatusBar.tsx
This is useful for copy/pasting version for support.
Fixes: https://github.com/pybricks/support/issues/1083
> status-bar: allow selection version

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/dependabot.yml
- .vscode/settings.json
- CONTRIBUTING.md
This adds a devcontainer config for devs to have an easy way to get a working dev environment.
> devcontainer: inital config

- src/firmware/sagas.ts
This was missed in the last commit.
> firmware/sagas: revert debug changes

- src/ble-pybricks-service/sagas.test.ts
I meant to change this before merging the previous commit, but missed it.
The mismatch test was hard to understand and didn't increase coverage, so let's leave it out.
> ble-pybricks-service/sagas: simplify test
